;;; yastylus-mode.el --- Major mode for editing .styl files
;;;
;;; URL: https://github.com/kuanyui/yastylus-mode.el
;;; Author: kuanyen (onohiroko) kuanyui.github.io
;;; Package-Requires: ((sws-mode "0"))

;;; Forked from Brian M. Carlson 's stylus-mode

;;;
(require 'font-lock)
(require 'sws-mode)

(defun yastylus-debug (string &rest args)
  "Prints a debug message"
  (apply 'message (append (list string) args)))

(defmacro yastylus-line-as-string ()
  "Returns the current line as a string."
  `(buffer-substring (point-at-bol) (point-at-eol)))


(defun yastylus-empty-line-p ()
  "If line is empty or not."
  (= (point-at-eol) (point-at-bol)))

(defun yastylus-blank-line-p ()
  "If line contains only spaces."
  (string-match-p "^[ ]*$" (yastylus-line-as-string)))

(defconst yastylus-colours
  (eval-when-compile
    (regexp-opt
     '("black" "silver" "gray" "white" "maroon" "red"
       "purple" "fuchsia" "green" "lime" "olive" "yellow" "navy"
       "blue" "teal" "aqua")))
  "Stylus keywords.")

(defconst yastylus-keywords
  (eval-when-compile
    (regexp-opt
     '("return" "if" "else" "unless" "for" "in" "true" "false")))
  "Stylus keywords.")

(setq yastylus-all-properties '(
                              "zoom"
                              "z-index"
                              "y"
                              "x"
                              "wrap"
                              "word-wrap"
                              "word-spacing"
                              "word-break"
                              "word"
                              "width"
                              "widows"
                              "white-space-collapse"
                              "white-space"
                              "white"
                              "weight"
                              "volume"
                              "voice-volume"
                              "voice-stress"
                              "voice-rate"
                              "voice-pitch-range"
                              "voice-pitch"
                              "voice-family"
                              "voice-duration"
                              "voice-balance"
                              "voice"
                              "visibility"
                              "vertical-align"
                              "variant"
                              "user-select"
                              "up"
                              "unicode-bidi"
                              "unicode-range"
                              "unicode"
                              "trim"
                              "transition-timing-function"
                              "transition-property"
                              "transition-duration"
                              "transition-delay"
                              "transition"
                              "transform"
                              "touch-action"
                              "top-width"
                              "top-style"
                              "top-right-radius"
                              "top-left-radius"
                              "top-color"
                              "top"
                              "timing-function"
                              "text-wrap"
                              "text-transform"
                              "text-shadow"
                              "text-replace"
                              "text-rendering"
                              "text-overflow"
                              "text-outline"
                              "text-justify"
                              "text-indent"
                              "text-height"
                              "text-emphasis"
                              "text-decoration"
                              "text-align-last"
                              "text-align"
                              "text"
                              "target-position"
                              "target-new"
                              "target-name"
                              "target"
                              "table-layout"
                              "tab-size"
                              "style-type"
                              "style-position"
                              "style-image"
                              "style"
                              "string-set"
                              "stretch"
                              "stress"
                              "stacking-strategy"
                              "stacking-shift"
                              "stacking-ruby"
                              "stacking"
                              "src"
                              "speed"
                              "speech-rate"
                              "speech"
                              "speak-punctuation"
                              "speak-numeral"
                              "speak-header"
                              "speak"
                              "span"
                              "spacing"
                              "space-collapse"
                              "space"
                              "sizing"
                              "size-adjust"
                              "size"
                              "shadow"
                              "respond-to"
                              "rule-width"
                              "rule-style"
                              "rule-color"
                              "rule"
                              "ruby-span"
                              "ruby-position"
                              "ruby-overhang"
                              "ruby-align"
                              "ruby"
                              "rows"
                              "rotation-point"
                              "rotation"
                              "role"
                              "right-width"
                              "right-style"
                              "right-color"
                              "right"
                              "richness"
                              "rest-before"
                              "rest-after"
                              "rest"
                              "resource"
                              "resize"
                              "reset"
                              "replace"
                              "repeat"
                              "rendering-intent"
                              "rate"
                              "radius"
                              "quotes"
                              "punctuation-trim"
                              "punctuation"
                              "property"
                              "profile"
                              "presentation-level"
                              "presentation"
                              "position"
                              "pointer-events"
                              "point"
                              "play-state"
                              "play-during"
                              "play-count"
                              "pitch-range"
                              "pitch"
                              "phonemes"
                              "pause-before"
                              "pause-after"
                              "pause"
                              "page-policy"
                              "page-break-inside"
                              "page-break-before"
                              "page-break-after"
                              "page"
                              "padding-top"
                              "padding-right"
                              "padding-left"
                              "padding-bottom"
                              "padding"
                              "pack"
                              "overhang"
                              "overflow-y"
                              "overflow-x"
                              "overflow-style"
                              "overflow"
                              "outline-width"
                              "outline-style"
                              "outline-offset"
                              "outline-color"
                              "outline"
                              "orphans"
                              "origin"
                              "orientation"
                              "orient"
                              "ordinal-group"
                              "order"
                              "opacity"
                              "offset"
                              "numeral"
                              "new"
                              "nav-up"
                              "nav-right"
                              "nav-left"
                              "nav-index"
                              "nav-down"
                              "nav"
                              "name"
                              "move-to"
                              "model"
                              "mix-blend-mode"
                              "min-width"
                              "min-height"
                              "min"
                              "max-width"
                              "max-height"
                              "max"
                              "marquee-style"
                              "marquee-speed"
                              "marquee-play-count"
                              "marquee-direction"
                              "marquee"
                              "marks"
                              "mark-before"
                              "mark-after"
                              "mark"
                              "margin-top"
                              "margin-right"
                              "margin-left"
                              "margin-bottom"
                              "margin"
                              "mask-image"
                              "list-style-type"
                              "list-style-position"
                              "list-style-image"
                              "list-style"
                              "list"
                              "lines"
                              "line-stacking-strategy"
                              "line-stacking-shift"
                              "line-stacking-ruby"
                              "line-stacking"
                              "line-height"
                              "line-break"
                              "level"
                              "letter-spacing"
                              "length"
                              "left-width"
                              "left-style"
                              "left-color"
                              "left"
                              "label"
                              "justify-content"
                              "justify"
                              "iteration-count"
                              "inline-box-align"
                              "initial-value"
                              "initial-size"
                              "initial-before-align"
                              "initial-before-adjust"
                              "initial-after-align"
                              "initial-after-adjust"
                              "index"
                              "indent"
                              "increment"
                              "image-resolution"
                              "image-orientation"
                              "image"
                              "icon"
                              "hyphens"
                              "hyphenate-resource"
                              "hyphenate-lines"
                              "hyphenate-character"
                              "hyphenate-before"
                              "hyphenate-after"
                              "hyphenate"
                              "height"
                              "header"
                              "hanging-punctuation"
                              "gap"
                              "grid"
                              "grid-area"
                              "grid-auto-columns"
                              "grid-auto-flow"
                              "grid-auto-rows"
                              "grid-column"
                              "grid-column-end"
                              "grid-column-start"
                              "grid-row"
                              "grid-row-end"
                              "grid-row-start"
                              "grid-template"
                              "grid-template-areas"
                              "grid-template-columns"
                              "grid-template-rows"
                              "row-gap"
                              "gap"
                              "font-kerning"
                              "font-language-override"
                              "font-weight"
                              "font-variant-caps"
                              "font-variant"
                              "font-style"
                              "font-synthesis"
                              "font-stretch"
                              "font-size-adjust"
                              "font-size"
                              "font-family"
                              "font"
                              "float-offset"
                              "float"
                              "flex-wrap"
                              "flex-shrink"
                              "flex-grow"
                              "flex-group"
                              "flex-flow"
                              "flex-direction"
                              "flex-basis"
                              "flex"
                              "fit-position"
                              "fit"
                              "fill"
                              "filter"
                              "family"
                              "empty-cells"
                              "emphasis"
                              "elevation"
                              "duration"
                              "drop-initial-value"
                              "drop-initial-size"
                              "drop-initial-before-align"
                              "drop-initial-before-adjust"
                              "drop-initial-after-align"
                              "drop-initial-after-adjust"
                              "drop"
                              "down"
                              "dominant-baseline"
                              "display-role"
                              "display-model"
                              "display"
                              "direction"
                              "delay"
                              "decoration-break"
                              "decoration"
                              "cursor"
                              "cue-before"
                              "cue-after"
                              "cue"
                              "crop"
                              "counter-reset"
                              "counter-increment"
                              "counter"
                              "count"
                              "content"
                              "columns"
                              "column-width"
                              "column-span"
                              "column-rule-width"
                              "column-rule-style"
                              "column-rule-color"
                              "column-rule"
                              "column-gap"
                              "column-fill"
                              "column-count"
                              "column-break-before"
                              "column-break-after"
                              "column"
                              "color-profile"
                              "color"
                              "collapse"
                              "clip"
                              "clear"
                              "character"
                              "caption-side"
                              "break-inside"
                              "break-before"
                              "break-after"
                              "break"
                              "box-sizing"
                              "box-shadow"
                              "box-pack"
                              "box-orient"
                              "box-ordinal-group"
                              "box-lines"
                              "box-flex-group"
                              "box-flex"
                              "box-direction"
                              "box-decoration-break"
                              "box-align"
                              "box"
                              "bottom-width"
                              "bottom-style"
                              "bottom-right-radius"
                              "bottom-left-radius"
                              "bottom-color"
                              "bottom"
                              "border-width"
                              "border-top-width"
                              "border-top-style"
                              "border-top-right-radius"
                              "border-top-left-radius"
                              "border-top-color"
                              "border-top"
                              "border-style"
                              "border-spacing"
                              "border-right-width"
                              "border-right-style"
                              "border-right-color"
                              "border-right"
                              "border-radius"
                              "border-length"
                              "border-left-width"
                              "border-left-style"
                              "border-left-color"
                              "border-left"
                              "border-image"
                              "border-color"
                              "border-collapse"
                              "border-bottom-width"
                              "border-bottom-style"
                              "border-bottom-right-radius"
                              "border-bottom-left-radius"
                              "border-bottom-color"
                              "border-bottom"
                              "border"
                              "bookmark-target"
                              "bookmark-level"
                              "bookmark-label"
                              "bookmark"
                              "binding"
                              "bidi"
                              "before"
                              "baseline-shift"
                              "baseline"
                              "balance"
                              "background-blend-mode"
                              "background-size"
                              "background-repeat"
                              "background-position"
                              "background-origin"
                              "background-image"
                              "background-color"
                              "background-clip"
                              "background-break"
                              "background-attachment"
                              "background"
                              "azimuth"
                              "attachment"
                              "appearance"
                              "animation-timing-function"
                              "animation-play-state"
                              "animation-name"
                              "animation-iteration-count"
                              "animation-duration"
                              "animation-direction"
                              "animation-delay"
                              "animation-fill-mode"
                              "animation"
                              "alignment-baseline"
                              "alignment-adjust"
                              "alignment"
                              "align-self"
                              "align-last"
                              "align-items"
                              "align-content"
                              "align"
                              "after"
                              "adjust"
                              "will-change"
                              "writing-mode"
                              "text-anchor"
                              "stroke-width"
                              "stroke-opacity"
                              "stroke-miterlimit"
                              "stroke-linejoin"
                              "stroke-linecap"
                              "stroke-dashoffset"
                              "stroke-dasharray"
                              "stroke"
                              "stop-opacity"
                              "stop-color"
                              "shape-rendering"
                              "marker-start"
                              "marker-mid"
                              "marker-end"
                              "lighting-color"
                              "kerning"
                              "image-rendering"
                              "glyph-orientation-vertical"
                              "glyph-orientation-horizontal"
                              "flood-opacity"
                              "flood-color"
                              "fill-rule"
                              "fill-opacity"
                              "fill"
                              "enable-background"
                              "color-rendering"
                              "color-interpolation-filters"
                              "color-interpolation"
                              "clip-rule"
                              "clip-path"))

(setq yastylus-properties
      (eval-when-compile
        (format "^ +?%s:? *" (regexp-opt yastylus-all-properties))))

(setq yastylus-font-lock-keywords
      `(
        (,yastylus-properties 0 font-lock-function-name-face)  ;; highest priority
        (,"\\(::?\\(root\\|nth-child\\|nth-last-child\\|nth-of-type\\|nth-last-of-type\\|first-child\\|last-child\\|first-of-type\\|last-of-type\\|only-child\\|only-of-type\\|empty\\|link\\|visited\\|active\\|hover\\|focus\\|target\\|lang\\|enabled\\|disabled\\|checked\\|not\\)\\)*" . font-lock-type-face) ;; pseudoSelectors
        (,(concat "[^_$]?\\<\\(" yastylus-colours "\\)\\>[^_]?") 0 font-lock-constant-face)
        (,(concat "[^_$]?\\<\\(" yastylus-keywords "\\)\\>[^_]?") 0 font-lock-keyword-face)
        (,"#\\w[a-zA-Z0-9\\-]+" 0 font-lock-keyword-face) ; id selectors (also colors...)
        (,"\\([.0-9]+:?\\(em\\|ex\\|px\\|mm\\|cm\\|in\\|pt\\|pc\\|deg\\|rad\\|grad\\|ms\\|s\\|Hz\\|kHz\\|rem\\|%\\)\\b\\)" 0 font-lock-constant-face)
        (,"\\b[0-9]+\\b" 0 font-lock-constant-face)
        (,"\\.\\w[a-zA-Z0-9_-]+" 0 font-lock-type-face) ; class names
        ;; (,"$\\w+" 0 font-lock-variable-name-face)
        (,"@\\w[a-zA-Z0-9\\-]+" 0 font-lock-preprocessor-face) ; directives and backreferences
        (,"[$a-z0-9_-]+" 0 font-lock-variable-name-face)  ;; all other may be variables
        ))
(setq yastylus-syntax-table
      (let ((syntable (make-syntax-table)))
        (modify-syntax-entry ?\/ ". 124b" syntable)
        (modify-syntax-entry ?* ". 23" syntable)
        (modify-syntax-entry ?\n "> b" syntable)
        (modify-syntax-entry ?- "_" syntable)
        (modify-syntax-entry ?_ "_" syntable)
        (modify-syntax-entry ?' "\"" syntable)
        syntable))
     ;;  "Syntax table for `yastylus-mode'.")

(defun yastylus-region-for-sexp ()
  "Selects the current sexp as the region"
  (interactive)
  (beginning-of-line)
  (let ((ci (current-indentation)))
    (push-mark nil nil t)
    (while (> (yastylus-next-line-indent) ci)
      (next-line)
      (end-of-line))))

(defvar yastylus-mode-map (make-sparse-keymap))
;;defer to sws-mode
;;(define-key yastylus-mode-map [S-tab] 'yastylus-unindent-line)

;; mode declaration
;;;###autoload
(define-derived-mode yastylus-mode sws-mode
  "Yastylus"
  "Major mode for editing yastylus node.js templates"
  (setq tab-width 2)

  (setq mode-name "Yastylus")
  (setq major-mode 'yastylus-mode)

  ;; syntax table
  (set-syntax-table yastylus-syntax-table)

  ;; highlight syntax
  (setq font-lock-defaults '(yastylus-font-lock-keywords))

  ;; comments
  (set (make-local-variable 'comment-start) "//")
  (set (make-local-variable 'comment-end) "")

  ;; default tab width
  (setq sws-tab-width 2)
  (make-local-variable 'indent-line-function)
  (setq indent-line-function 'sws-indent-line)
  (make-local-variable 'indent-region-function)

  (setq indent-region-function 'sws-indent-region)

  ;; keymap
  (use-local-map yastylus-mode-map))

;;;###autoload
(add-to-list 'auto-mode-alist '("\\.styl\\'" . yastylus-mode))

(provide 'yastylus-mode)
;;; yastylus-mode.el ends here
